version: "2"
services:
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./dev1.cloud_test.pl:/var/www/dev1.cloud_test.pl
            - ./private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
            - ./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
            - ./certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
            - ./snippets/self-signed.conf:/etc/nginx/snippets/self-signed.conf
            - ./snippets/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
        restart: always
